### ISSUE TITLE
extra trace produced when using logging and trace

### ISSUE THREAD

**Issue by savaki** [GoogleCloudPlatform/google-cloud-go#1008]
(delete this for feature requests)

## Client

Google's logging client and stackdriver trace client.

cloud.google.com/go/logging
contrib.go.opencensus.io/exporter/stackdriver

## Describe Your Environment

go 1.10 on OS X

## Expected Behavior

When I submit a trace via stackdriver AND I use google's logging client, I only expect to see the trace I posted.  

## Actual Behavior

What I see instead is the trace I submitted (via stackdriver) AND a trace submitted by what appears to be the logging service.  The URI of the extra trace is:

```Sent.google.logging.v2.LoggingServiceV2.WriteLogEntries```

I put together a minimal example that demonstrates the problem.

```go
package main

import (
	"context"
	"log"
	"time"

	"cloud.google.com/go/logging"
	"contrib.go.opencensus.io/exporter/stackdriver"
	"go.opencensus.io/trace"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/option"
)

const (
	gcpCredentials = `your-json-credentials-here`
)

func check(err error) {
	if err != nil {
		log.Fatalln(err)
	}
}

func main() {
	ctx := context.Background()

	credentials, err := google.CredentialsFromJSON(ctx, []byte(gcpCredentials),
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/trace.append",
		"https://www.googleapis.com/auth/trace.readonly",
		logging.WriteScope,
	)
	check(err)

	exporter, err := stackdriver.NewExporter(stackdriver.Options{
		ProjectID: credentials.ProjectID,
		TraceClientOptions: []option.ClientOption{
			option.WithCredentials(credentials),
		},
	})
	check(err)
	defer exporter.Flush()
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	trace.RegisterExporter(exporter)

	client, err := logging.NewClient(ctx, credentials.ProjectID, option.WithCredentials(credentials))
	check(err)
	defer client.Close()
	logger := client.Logger("example", logging.EntryCountThreshold(1))

	example(ctx, logger)
	time.Sleep(2 * time.Second)
}

// example should generate 1 trace, not two.  currently, it generates two traces.
func example(ctx context.Context, logger *logging.Logger) error {
	ctx, span := trace.StartSpan(ctx, "example")
	defer span.End()

	time.Sleep(125 * time.Millisecond)
	logger.Log(logging.Entry{Payload: "hello example"})
	time.Sleep(125 * time.Millisecond)

	return nil
}
```

**Comment by jadekler** [comment]
All outgoing requests automatically get a span; in this case, under the hood we are adding a span when you submit a request during `logger.Log`. They should appear nested in stackdriver; it should be that "example" is the parent and "WriteLogEntries" is the child.

All clients exhibit this behavior - all outgoing requests have spans added to them.

**Comment by savaki** [comment]
This screenshot shows a single function with a single span that has 4 calls to Log within it.  You can see that in the trace list, the automatically created log traces overshadow the 1 trace I actually created, example.

[screenshot](https://imgur.com/a/RAiTtue)

Is this the expected behavior?

**Comment by jadekler** [comment]
Hm, that's odd to me - I would have only expect 1 log span. Is that screenshot from the above code, or is it with code that has a for loop or something? Is it always 4?

**Comment by savaki** [comment]
It's always equal to the number of calls to logger.Log.  If you take the above code and repeat the "hello example" line multiple times, you'll get multiple traces.

**Comment by jadekler** [comment]
Ok, so you have 4 calls to logger.Log? Then yes, I expect to see 4 WriteLogEntries spans. Each log should product 1 span since you have `logging.EntryCountThreshold(1)`. If you were to set that higher, more entries would get batched together resulting in less calls (and, subsequently, less spans).

**Comment by jadekler** [comment]
Not at the moment, but I'll change this issue to a feature request.

**Comment by ramonza** [comment]
@savaki can you change your logging client initialization to:
```go
logCtx := context.Background()
logCtx, logSpan := trace.StartSpan(logCtx, "logging - ignored", trace.WithSampler(trace.NeverSample()))
defer logSpan.End()
client, err := logging.NewClient(logCtx, credentials.ProjectID, option.WithCredentials(credentials))
```

I do think that doing an RPC per log line is probably not what you intend, right? Is there a reason you're disabling buffering (EntryCountThreshold) or is this just to demonstrate this code?

Just to make sure I'm getting it: the real problem here is that the log calls appear as separate traces instead of nested under the "example" span in one trace, is that right? If so, I think the only way to fix this would be for the logger.Log call to take a context.Context that it would pass down to the gRPC layer.

**Comment by jba** [comment]
The way to avoid all trace samples for a client is to pass a span that is marked "never sample" when constructing the client:

```go
nctx, span := trace.StartSpan(ctx, "this span will not be exported",
        trace.WithSampler(trace.NeverSample()))
defer span.End()
client, err := xyz.NewClient(nctx, ...)
```

**Comment by savaki** [comment]
Sorry for the slow response.  That worked.  It seems strange to me that the default behavior is to generate those log traces.  That seems the more surprising path than allowing teams to enable tracing if they want.

**Comment by savaki** [comment]
Ok, spoke too soon.  It didn't work, but I've been too busy to follow up and we've just been living with it.  I finally tracked down the offending code.  This is from `cloud.google.com/go@v0.27.0/logging/logging.go` lines`755 - 768`.  The problem is that the context that's created is out of my control so there's no way to use  what @jba suggested.

```
func (l *Logger) writeLogEntries(entries []*logpb.LogEntry) {
	req := &logpb.WriteLogEntriesRequest{
		LogName:  l.logName,
		Resource: l.commonResource,
		Labels:   l.commonLabels,
		Entries:  entries,
	}
	ctx, cancel := context.WithTimeout(context.Background(), defaultWriteTimeout)
	defer cancel()
	_, err := l.client.client.WriteLogEntries(ctx, req)
	if err != nil {
		l.client.error(err)
	}
}
```

**Comment by savaki** [comment]
And for more context, here's the call stack from this invocation of `writeLogEntries` up to the point where `StartSpan` is called.

```
goroutine 112 [running]:
runtime/debug.Stack(0xc00000e018, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
go.opencensus.io/trace.StartSpan(0x2210140, 0xc0009bce10, 0xc0009820c0, 0x32, 0xc0008218f0, 0x2, 0x2, 0xc0009820c0, 0x32, 0xc0009bce10)
	/Users/matt/go/pkg/mod/go.opencensus.io@v0.15.0/trace/trace.go:156 +0x49
go.opencensus.io/plugin/ocgrpc.(*ClientHandler).traceTagRPC(0xc0002385f0, 0x2210140, 0xc0009bce10, 0xc0003345a0, 0x2210101, 0xc0003345a0)
	/Users/matt/go/pkg/mod/go.opencensus.io@v0.15.0/plugin/ocgrpc/trace_common.go:39 +0x175
go.opencensus.io/plugin/ocgrpc.(*ClientHandler).TagRPC(0xc0002385f0, 0x2210140, 0xc0009bce10, 0xc0003345a0, 0xc0009bce10, 0x0)
	/Users/matt/go/pkg/mod/go.opencensus.io@v0.15.0/plugin/ocgrpc/client.go:53 +0x4d
google.golang.org/grpc.newClientStream(0x2210080, 0xc000331280, 0x2cd5080, 0xc000478300, 0x208258a, 0x33, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/matt/go/pkg/mod/google.golang.org/grpc@v1.14.0/stream.go:237 +0xb7e
google.golang.org/grpc.invoke(0x2210140, 0xc0009bcd50, 0x208258a, 0x33, 0x1fc4280, 0xc0008bb4a0, 0x1f42ce0, 0xc000334580, 0xc000478300, 0x0, ...)
	/Users/matt/go/pkg/mod/google.golang.org/grpc@v1.14.0/call.go:66 +0x9c
google.golang.org/grpc.(*ClientConn).Invoke(0xc000478300, 0x2210140, 0xc0009bcd50, 0x208258a, 0x33, 0x1fc4280, 0xc0008bb4a0, 0x1f42ce0, 0xc000334580, 0x0, ...)
	/Users/matt/go/pkg/mod/google.golang.org/grpc@v1.14.0/call.go:37 +0x1b3
google.golang.org/genproto/googleapis/logging/v2.(*loggingServiceV2Client).WriteLogEntries(0xc000338080, 0x2210140, 0xc0009bcd50, 0xc0008bb4a0, 0x0, 0x0, 0x0, 0x10, 0x20, 0xc000334560)
	/Users/matt/go/pkg/mod/google.golang.org/genproto@v0.0.0-20180831171423-11092d34479b/googleapis/logging/v2/logging.pb.go:771 +0xd2
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries.func1(0x2210140, 0xc0009bcd50, 0x0, 0x0, 0x0, 0x0, 0xc000821db8, 0x100e0e8)
	/Users/matt/go/pkg/mod/cloud.google.com/go@v0.27.0/logging/apiv2/logging_client.go:162 +0x84
github.com/googleapis/gax-go.invoke(0x2210140, 0xc0009bcd50, 0xc000334540, 0x0, 0x0, 0x0, 0x0, 0x20a4058, 0x100e0e8, 0x20)
	/Users/matt/go/pkg/mod/github.com/googleapis/gax-go@v2.0.0+incompatible/invoke.go:70 +0x90
github.com/googleapis/gax-go.Invoke(0x2210140, 0xc0009bcd50, 0xc000334540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/go/pkg/mod/github.com/googleapis/gax-go@v2.0.0+incompatible/invoke.go:48 +0xf6
cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries(0xc000254840, 0x2210140, 0xc0009bcd50, 0xc0008bb4a0, 0x0, 0x0, 0x0, 0xc000334440, 0x106f265, 0x20a70a8)
	/Users/matt/go/pkg/mod/cloud.google.com/go@v0.27.0/logging/apiv2/logging_client.go:160 +0x1d1
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000051980, 0xc0002e0800, 0x75, 0x80)
	/Users/matt/go/pkg/mod/cloud.google.com/go@v0.27.0/logging/logging.go:764 +0x153
cloud.google.com/go/logging.(*Client).Logger.func1(0x1d335c0, 0xc000334440)
	/Users/matt/go/pkg/mod/cloud.google.com/go@v0.27.0/logging/logging.go:416 +0x5a
google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1(0xc0001ec240, 0x1d335c0, 0xc000334440, 0x97, 0x4c8b, 0x1)
	/Users/matt/go/pkg/mod/google.golang.org/api@v0.0.0-20180904000447-0ad5a633fea1/support/bundler/bundler.go:272 +0xd4
created by google.golang.org/api/support/bundler.(*Bundler).startFlushLocked
	/Users/matt/go/pkg/mod/google.golang.org/api@v0.0.0-20180904000447-0ad5a633fea1/support/bundler/bundler.go:266 +0xfc
```
