### ISSUE TITLE
CloudSpanner: SIGSEGV in bazel building environment

### ISSUE THREAD

**Issue by mjhd-devlion** [GoogleCloudPlatform/google-cloud-go#1017]
(delete this for feature requests)

## Client
CloudSpanner

## Describe Your Environment
OS: macOS High Sierra
go: version go1.10.2 darwin/amd64
Bazel: 0.13.1-homebrew

## Expected Behavior
No errors.

## Actual Behavior
[Here is code to reproduce.](https://github.com/mjhd-devlion/bazel-spanner-bug)
When I `go run`, there were no errors, but `bazel run`, displayed following errors:
```
~/.go/src/github.com/mjhd-devlion/bazel-spanner-bug » bazel run //:repro                                                                                                                    s01052@50-84035
INFO: Analysed target //:repro (96 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/com_google_protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/external/com_google_protobuf/src/google/protobuf/io/gzip_stream.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/external/com_google_protobuf/src/google/protobuf/util/internal/error_listener.o has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/external/com_google_protobuf/src/google/protobuf/arenastring.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/external/com_google_protobuf/src/google/protobuf/stubs/atomicops_internals_x86_msvc.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/external/com_google_protobuf/src/google/protobuf/stubs/io_win32.o has no symbols
Target //:repro up-to-date:
  bazel-bin/darwin_amd64_stripped/repro
INFO: Elapsed time: 122.332s, Critical Path: 31.68s
INFO: 287 processes: 284 darwin-sandbox, 3 local.
INFO: Build completed successfully, 292 total actions

INFO: Running command line: bazel-bin/darwin_amd64_stripped/repro
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x114ed88]

goroutine 1 [running]:
vendor/github.com/golang/protobuf/proto.makeOneOfMarshaler.func1(0xc42014f170, 0x0, 0x8)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:2281 +0x128
vendor/github.com/golang/protobuf/proto.(*marshalInfo).size(0xc42038b570, 0xc42014f170, 0xc4204c48e0)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:182 +0xaa
vendor/github.com/golang/protobuf/proto.makeMessageSliceMarshaler.func1(0xc4200a3c40, 0x1, 0x8)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:2170 +0x74
vendor/github.com/golang/protobuf/proto.(*marshalInfo).size(0xc42038b1f0, 0xc4200a3c40, 0x1552080)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:182 +0xaa
vendor/github.com/golang/protobuf/proto.makeMessageSliceMarshaler.func1(0xc42014cc00, 0x1, 0x8)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:2170 +0x74
vendor/github.com/golang/protobuf/proto.(*marshalInfo).size(0xc42038a700, 0xc42014cc00, 0x8)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:182 +0xaa
vendor/github.com/golang/protobuf/proto.makeMessageMarshaler.func1(0xc4200ac100, 0x1, 0x6)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:2145 +0x44
vendor/github.com/golang/protobuf/proto.(*marshalInfo).size(0xc42038a380, 0xc4200ac0b0, 0x193b520)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:182 +0xaa
vendor/github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(0x193b520, 0x1660340, 0xc4200ac0b0, 0x1fa01e0)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:124 +0x65
vendor/google.golang.org/genproto/googleapis/spanner/v1.(*ReadRequest).XXX_Size(0xc4200ac0b0, 0x1660340)
	vendor/google.golang.org/genproto/googleapis/spanner/v1/spanner.pb.go:971 +0x43
vendor/github.com/golang/protobuf/proto.(*Buffer).Marshal(0xc4201f8248, 0x1660340, 0xc4200ac0b0, 0xc4204aa120, 0x0)
	vendor/github.com/golang/protobuf/proto/table_marshal.go:2645 +0x8a
vendor/google.golang.org/grpc/encoding/proto.marshal(0x15d0780, 0xc4200ac0b0, 0xc4201f8240, 0x0, 0x0, 0x156a100, 0xc4201d2900, 0xc4201d2900)
	vendor/google.golang.org/grpc/encoding/proto/proto.go:59 +0xda
vendor/google.golang.org/grpc/encoding/proto.codec.Marshal(0x15d0780, 0xc4200ac0b0, 0x161b840, 0xc4201c79c8, 0x10, 0xc420000180, 0x161b840)
	vendor/google.golang.org/grpc/encoding/proto/proto.go:74 +0xaf
vendor/google.golang.org/grpc.encode(0x1e0d1f8, 0x19598d0, 0x15d0780, 0xc4200ac0b0, 0x0, 0x0, 0xc420278300, 0x0, 0x0, 0x0, ...)
	vendor/google.golang.org/grpc/rpc_util.go:494 +0x26e
vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc4201540d0, 0x15d0780, 0xc4200ac0b0, 0x0, 0x0)
	vendor/google.golang.org/grpc/stream.go:475 +0x111
vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc4201cc280, 0x15d0780, 0xc4200ac0b0, 0x192efc0, 0x1608c93)
	vendor/google.golang.org/grpc/stream.go:390 +0x43
vendor/google.golang.org/genproto/googleapis/spanner/v1.(*spannerClient).StreamingRead(0xc4200b25b8, 0x16610c0, 0xc4201f8390, 0xc4200ac0b0, 0x0, 0x0, 0x0, 0x0, 0x149f201, 0xc4201d28a0, ...)
	vendor/google.golang.org/genproto/googleapis/spanner/v1/spanner.pb.go:1587 +0x144
vendor/cloud.google.com/go/spanner.(*txReadOnly).ReadWithOptions.func2(0x16610c0, 0xc4201f8390, 0x0, 0x0, 0x0, 0x20, 0x16645e0, 0xc4200b25b8, 0xc4204c45e0)
	vendor/cloud.google.com/go/spanner/transaction.go:112 +0x209
vendor/cloud.google.com/go/spanner.(*resumableStreamDecoder).next(0xc420188180, 0x148dd1a)
	vendor/cloud.google.com/go/spanner/read.go:392 +0x398
vendor/cloud.google.com/go/spanner.(*RowIterator).Next(0xc420278180, 0x161ac70, 0xc420278180, 0x15f435d)
	vendor/cloud.google.com/go/spanner/read.go:86 +0x7d
vendor/cloud.google.com/go/spanner.(*txReadOnly).ReadRow(0xc4200d3680, 0x1661040, 0xc4200a0008, 0x15f435d, 0x4, 0xc4201a6420, 0x1, 0x1, 0xc4201a6430, 0x1, ...)
	vendor/cloud.google.com/go/spanner/transaction.go:141 +0x14a
main.main()
	main.go:21 +0x19d
ERROR: Non-zero return code '2' from command: Process exited with status 2
```

**Comment by jba** [comment]
I don't know what would cause this to fail. Are you compiling the same files with `go` as you are with `bazel`? Have you tried it at head? My suspicion is some skew between the protobuf code and the spanner client code, but I'm not sure.

**Comment by mjhd-devlion** [comment]
> Are you compiling the same files with go as you are with bazel?
yes, I'm compiling same files in same directory.

**Comment by mjhd-devlion** [comment]
I found that this problem was caused by [rules_go](https://github.com/bazelbuild/rules_go)'s [dependency resolving behavior](https://github.com/bazelbuild/bazel-gazelle/commit/257c283f6dd0d177cad931f3e6897f07fed5b41e).
I will find a way to resolve dependency correctly by gazelle config.
Thank you.
