### ISSUE TITLE
Datastore Viewer internal error(s)

### ISSUE THREAD

**Issue by kevvurs** [GoogleCloudPlatform/google-cloud-go#1032]
## Client
Datastore (emulator)
App Engine Standard

## Describe Your Environment
Ubuntu 18.04
Go 1.9.6
Google Cloud SDK 204.0.0
app-engine-go 
app-engine-python 1.9.70
beta 2017.09.15
bigtable 
bq 2.0.34
cbt 
cloud-datastore-emulator 2.0.0
core 2018.06.04
gsutil 4.31

## Expected Behavior
- Open screen
- Run datastore emulator in screen
- Detach screen
- Set environment variables
- Run local app engine server
- Enter Datastore Viewer

```
screen -S datastore
gcloud beta emulators datastore start
<detach>
$(gcloud beta emulators datastore env-init)
dev_appserver.py app.yaml --port=3001 -A my-project-id --support_datastore_emulator=true
```

(The environment variable were set as expected. App Engine dev-server appears to function properly.)

## Actual Behavior
Datastore Viewer crashes on error when opened in Firefox window at http://localhost:8000/datastore.

> Traceback (most recent call last):
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/admin_request_handler.py", line 87, in dispatch
    super(AdminRequestHandler, self).dispatch()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/datastore_viewer.py", line 668, in get
    kinds = self._get_kinds(namespace)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/datastore_viewer.py", line 603, in _get_kinds
    return sorted([x.kind_name for x in q.run()])
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/ext/db/__init__.py", line 2080, in run
    iterator = raw_query.Run(**kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 1698, in Run
    itr = Iterator(self.GetBatcher(config=config))
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 1677, in GetBatcher
    return self.GetQuery().run(_GetConnection(), query_options)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 410, in _GetConnection
    __InitConnection()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 401, in __InitConnection
    adapter=_adapter)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2800, in _CreateDefaultConnection
    kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2838, in _CreateCloudDatastoreConnection
    datastore_pbs.MISSING_CLOUD_DATASTORE_MESSAGE)
BadArgumentError: Could not import googledatastore. This library must be installed with version >= 6.0.0 to use the Cloud Datastore API.

I ran `gcloud components update` but the error persists. [My source is public.](https://github.com/kevvurs/content-etl)

This sucks. I get blocked for a day. Finally, I find on StackOverflow that I can install googledatastore manually with pip. (Pretty lame). Now it is installed. The error changes to the following.

> Traceback (most recent call last):
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/admin_request_handler.py", line 87, in dispatch
    super(AdminRequestHandler, self).dispatch()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/datastore_viewer.py", line 668, in get
    kinds = self._get_kinds(namespace)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/admin/datastore_viewer.py", line 603, in _get_kinds
    return sorted([x.kind_name for x in q.run()])
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/ext/db/__init__.py", line 2080, in run
    iterator = raw_query.Run(**kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 1698, in Run
    itr = Iterator(self.GetBatcher(config=config))
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 1677, in GetBatcher
    return self.GetQuery().run(_GetConnection(), query_options)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 410, in _GetConnection
    __InitConnection()
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 401, in __InitConnection
    adapter=_adapter)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2800, in _CreateDefaultConnection
    kwargs)
  File "/media/kevvurs/ExtraDrive1/pro/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2846, in _CreateCloudDatastoreConnection
    'already connected to (%s).' % (app_id, current_app_id))
ValueError: Cannot create a Cloud Datastore context that connects to an application (my-project-id) that differs from the application already connected to (dev~my-project-id).

Obviously, "my-project-id" is my actual ID. At this point, on dev server, the app ID I submit with -A gets prepended with "dev~" and that breaks the connection to the emulator (it should not).

## Comment
I have reviewed the docs, such as https://cloud.google.com/datastore/docs/tools/datastore-emulator, numerous times. At this point, even if it is somehow not a bug and the software is supposed to break down this way, it contributes to poor DX.

**Comment by jba** [comment]
This issues doesn't actually reference any code in this repo. (The code uses the appengine datastore client.) 

@broady @zombiezen any idea where to file it?

**Comment by zombiezen** [comment]
Based on https://cloud.google.com/support/docs/issue-trackers, the right place to file seems to be on [the Cloud SDK](https://issuetracker.google.com/issues/new?component=187143&template=0).

**Comment by kevvurs** [comment]
Fair enough. Will kick the can down the road then. Thanks for pointing me in the right direction.
