### ISSUE TITLE
datastore: RunInTransaction fails to retry with emulator

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-go#1218]
## Client

Datastore

## Describe Your Environment

Mac OS X 10.14

## Expected Behavior

When using the Datastore emulator, we should be able to write tests where multiple Goroutines try to commit a transaction that conflicts using `RunInTransaction`. This should cause some of the transactions to abort and retry. Eventually, they should all succeed.

## Actual Behavior

We get errors with gRPC status code `Unknown`, because the emulator does not correctly implement the Commit API. The logs show that it detects the conflict (see below). This causes the Go `RunInTransaction` to return the error, and some of our clients to fail.

A solution would be to have `RunInTransaction` retry on both `Aborted` and `Unknown`. In fact, this may be a "correct" solution, even for the real Datastore: in theory it should be safe to retry commits, since if it is already committed, we should get a response that indicates that.

Another solution would be to fix the emulator to not do this. I filed a GCP issue : https://issuetracker.google.com/issues/119520139 . I also found a previous report https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/201

## Datastore emulator logs

```
[datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@37c19d8
[datastore] com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.datastore.core.exception.DatastoreException: too much contention on these datastore entities. please try again.
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4816)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache.exists(CloudDatastoreV1.java:331)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.applyMutation(CloudDatastoreV1.java:750)[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:693)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.commit(CloudDatastoreV1.java:374)
[datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreV1Emulator.commit(DatastoreV1Emulator.java:132)
[datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter$1.commit(DatastoreEmulatorGrpcAdapter.java:155)
[datastore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:861)
[datastore]     at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
[datastore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
[datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:650)
[datastore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[datastore]     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[datastore]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
[datastore]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
[datastore]     at java.lang.Thread.run(Thread.java:748)
[datastore] Caused by: com.google.cloud.datastore.core.exception.DatastoreException: too much contention on these datastore entities. please try again.
[datastore]     at com.google.cloud.datastore.emulator.impl.Utils.newError(Utils.java:75)
[datastore]     at com.google.cloud.datastore.emulator.impl.Utils.newError(Utils.java:79)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$EntityGroupTracker.checkEntityGroupVersion(BaseLocalDatastore.java:2220)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$LiveTxn.trackEntityGroup(BaseLocalDatastore.java:2121)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$Profile$EntityGroup.addTransaction(BaseLocalDatastore.java:1304)
[datastore]     at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore.get(BaseLocalDatastore.java:507)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache$1.load(CloudDatastoreV1.java:311)
[datastore]     at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1$ExistenceCache$1.load(CloudDatastoreV1.java:306)
[datastore]     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3453)
[datastore]     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2170)
[datastore]     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2129)
[datastore]     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2042)
[datastore]     at com.google.common.cache.LocalCache.get(LocalCache.java:3879)
[datastore]     at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3883)
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4808)
[datastore]     at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4814)
[datastore]     ... 15 more
[datastore]
```

**Comment by enocom** [comment]
Seems this should be a change to the emulator and not the client.

WDYT @jadekler?

**Comment by jadekler** [comment]
Seems reasonable to me!

**Comment by evanj** [comment]
Seems reasonable to me. Would you mind bugging whatever team that does own this about the above tickets? Thanks!

**Comment by jadekler** [comment]
Done.
