### ISSUE TITLE
speech/apiv1beta1: init panics

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#379]
Consider importing the speech/apiv1beta1 in a program:

```
import speech "cloud.google.com/go/speech/apiv1beta1"
```

It panics when trying to run.

```
panic: () (0xc4200149b0,0x10000c420014801)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 1 [running]:
panic(0x3c34e0, 0x63de70)
	/Users/jbd/go/src/runtime/panic.go:496 +0x1a0
sort.(*reverse).Len(0xc4200149a0, 0x110f8)
	<autogenerated>:19 +0x49
sort.Sort(0x625d80, 0xc4200149a0)
	/Users/jbd/go/src/sort/sort.go:216 +0x31
net.init.1()
	/Users/jbd/go/src/net/addrselect.go:293 +0xc6
net.init()
	net/_obj/_cgo_import.go:11 +0xdb3
crypto/x509.init()
	crypto/x509/_obj/_cgo_import.go:24 +0xaa
crypto/tls.init()
	/Users/jbd/go/src/crypto/tls/tls.go:298 +0x73
net/http.init()
	/Users/jbd/go/src/net/http/transport.go:2168 +0x4b
golang.org/x/net/trace.init()
	/Users/jbd/src/golang.org/x/net/trace/trace.go:1064 +0x78
google.golang.org/grpc.init()
	/Users/jbd/src/google.golang.org/grpc/trace.go:120 +0x78
github.com/googleapis/gax-go.init()
	/Users/jbd/src/github.com/googleapis/gax-go/path_template_parser.go:228 +0x3a
cloud.google.com/go/speech/apiv1beta1.init()
	/Users/jbd/src/cloud.google.com/go/speech/apiv1beta1/speech_client.go:156 +0x3f
main.init()
	/Users/jbd/src/github.com/GoogleCloudPlatform/golang-samples/speech/caption/caption.go:82 +0x4e
exit status 2
```

**Comment by bradfitz** [comment]
How big's your binary? Which architecture?

**Comment by bradfitz** [comment]
I assume Darwin too from `/Users/jbd`

**Comment by rakyll** [comment]
Happens against the go tip, wrong issue tracker to report.

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jbd"
GORACE=""
GOROOT="/Users/jbd/go"
GOTOOLDIR="/Users/jbd/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/00/1b8h8000h01000cxqpysvccm005d21/T/go-build016652123=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by rakyll** [comment]
(Works fine against 1.7.1, if it is not clear from the previous message. I will file a bug soon, currently I am traveling.)
