### ISSUE TITLE
trace: panics with concurrent map write

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#584]
```
fatal error: concurrent map writes

goroutine 12 [running]:
runtime.throw(0x15497a4, 0x15)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:596 +0x95 fp=0xc42003dd40 sp=0xc42003dd20
runtime.mapassign(0x14a8f60, 0xc42015c8a0, 0xc42003def8, 0x1550b06)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/hashmap.go:589 +0x2a1 fp=0xc42003dde0 sp=0xc42003dd40
redacted/vendor/cloud.google.com/go/trace.(*trace).constructTrace(0xc420162300, 0xc420166300, 0xb, 0x10, 0x0)
	/Users/ahmetb/workspace/gopath-redacted/src/redacted/vendor/cloud.google.com/go/trace/trace.go:540 +0x89a fp=0xc42003df28 sp=0xc42003dde0
redacted/vendor/cloud.google.com/go/trace.(*trace).finish.func1(0xc420162300, 0xc420166300, 0xb, 0x10)
	/Users/ahmetb/workspace/gopath-redacted/src/redacted/vendor/cloud.google.com/go/trace/trace.go:519 +0x67 fp=0xc42003dfc0 sp=0xc42003df28
runtime.goexit()
	/usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42003dfc8 sp=0xc42003dfc0
created by redacted/vendor/cloud.google.com/go/trace.(*trace).finish
	/Users/ahmetb/workspace/gopath-redacted/src/redacted/vendor/cloud.google.com/go/trace/trace.go:527 +0x28c
```

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/c/11631/, though this smells like a user bug. SetLabel shouldn't be called after Finish is called.

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/c/11632 to improve the docs. I'd prefer to abandon CL/11631 if there are no other source of data races due to label setting.

**Comment by ahmetb** [comment]
Thanks. Is there any value in panicking if user calls SetLabel after Finish (assuming there's an easy way to detect)?

**Comment by rakyll** [comment]
Being more defensive might be good.

**Comment by rakyll** [comment]
I decided to guard SetLabel and will follow up with some doc improvements. Label setting might likely to be used concurrently by the user through the lifecycle of span to collect data. It is worth to have a mutex.
