### ISSUE TITLE
bigquery: handling null/nil results

### ISSUE THREAD

**Issue by tonglil** [GoogleCloudPlatform/google-cloud-go#593]
https://godoc.org/cloud.google.com/go/bigquery#example-RowIterator-Next-Struct

In the above example, how can I check/handle a query that returns no results (running the query in the UI is null)?

Currently if I pass a struct (like the one in the example but `float64` vs `int`) to `it.Next()`, it will panic like:
```
panic: interface conversion: interface {} is nil, not float64

goroutine 55 [running]:
cloud.google.com/go/bigquery.setFloat(0x15a7c20, 0xc420497658, 0x18e, 0x0, 0x0, 0x1, 0x15a7c20)
	/Users/207383/Code/go/src/cloud.google.com/go/bigquery/value.go:121 +0x218
cloud.google.com/go/bigquery.runOps(0xc4202ba720, 0x1, 0x1, 0x15fe860, 0xc420497658, 0x199, 0xc42056e3f0, 0x1, 0x1, 0x0, ...)
	/Users/207383/Code/go/src/cloud.google.com/go/bigquery/value.go:297 +0x21f
cloud.google.com/go/bigquery.(*structLoader).Load(0xc420488b08, 0xc42056e3f0, 0x1, 0x1, 0xc42023e010, 0x1, 0x1, 0x0, 0x13d79e6)
	/Users/207383/Code/go/src/cloud.google.com/go/bigquery/value.go:285 +0xcf
cloud.google.com/go/bigquery.(*RowIterator).Next(0xc420488a90, 0x158ce40, 0xc420497658, 0xc420488a90, 0x0)
	/Users/207383/Code/go/src/cloud.google.com/go/bigquery/iterator.go:123 +0x146
```

**Comment by jba** [comment]
You can't use structs with null values. Use a map or slice of `bigquery.Value` instead. For example:
```go
var m map[string]bigquery.Value
err := it.Next(&m)
```

We should document this better, and avoid panicking.
