### ISSUE TITLE
http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#663]
When I integrate multiple Google APIs into my program, I start getting the following error. Details below.

```
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x18a7780, 0x15d8e89, 0xf, 0x185a8e0, 0x15f0948)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2254 +0x610
net/http.(*ServeMux).HandleFunc(0x18a7780, 0x15d8e89, 0xf, 0x15f0948)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2286 +0x55
net/http.HandleFunc(0x15d8e89, 0xf, 0x15f0948)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2298 +0x4b
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace.init.1()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace/trace.go:121 +0x42
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace/trace_go17.go:22 +0x1cd
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/trace.go:120 +0x7d
github.com/ahmetb/gcb-dashboard/vendor/github.com/googleapis/gax-go.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/github.com/googleapis/gax-go/path_template_parser.go:228 +0x4e
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/internal.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/internal/retry.go:56 +0x53
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/compute/metadata.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/compute/metadata/metadata.go:439 +0x8c
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/google.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/google/sdk.go:173 +0x8c
main.init()
	/Users/ahmetb/workspace/gopath-gcb-dashboard/src/github.com/ahmetb/gcb-dashboard/triggers.go:54 +0x87
exit status 2
```

I initially had this:

```go
import (
	cloudbuild "google.golang.org/api/cloudbuild/v1"
	sourcerepo "google.golang.org/api/sourcerepo/v1"
)
...
	ts, err := google.DefaultTokenSource(ctx, cloudbuild.CloudPlatformScope) // omitted err handling

	cb, err := cloudbuild.New(oauth2.NewClient(ctx, ts)) // omitted err handling
	sr, err := sourcerepo.New(oauth2.NewClient(ctx, ts)) // omitted err handling
```

The code above  this works fine. The moment I add the following, it starts panicking:

```go
import iam "cloud.google.com/go/iam/admin/apiv1"

iamCl, err := iam.NewIamClient(ctx) // omitted err handling
```

It looks like `vendor/golang.org/x/net/trace/trace.go` is the culprit:
```
112-func init() {
113:	http.HandleFunc("/debug/requests", func(w http.ResponseWriter, req *http.Request) {
114-		any, sensitive := AuthRequest(req)
```

I assume this is happening because `iam` package is not yet vendored, but is in GOPATH (because I just did `go get`). Go list confirms:

```
$ go list ./... | grep trace
cloud.google.com/go/internal/tracecontext
cloud.google.com/go/trace
cloud.google.com/go/trace/apiv1
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace     <------ this
golang.org/x/net/trace                                    <------ this
google.golang.org/api/cloudtrace/v1
google.golang.org/genproto/googleapis/devtools/cloudtrace/v1
```

**Comment by broady** [comment]
Yes, that is a bad side effect of vendoring.

**Comment by ahmetb** [comment]
@broady hmm maybe x/net/trace should not register if it's already registered.

**Comment by jba** [comment]
@broady What is the fix?

**Comment by Bo0mer** [comment]
I think it is related to https://github.com/golang/go/issues/20478.

**Comment by ahmetb** [comment]
This particular error was because `x/net/trace` was imported from both vendored and non-vendored paths as a result of partial vendoring. I am not sure if there's anything we can do in this repo to fix it. I left some comments about the side-effect init function to the issue linked in the previous comment.

**Comment by rakyll** [comment]
Given you are experiencing the problem due to reasons not related to Cloud packages but vendoring, I am closing this issue. Please let us know/reopen the issue if we can help any further.
