### ISSUE TITLE
vision: Error happens when a program imports grpc more than twice

### ISSUE THREAD

**Issue by avelino** [GoogleCloudPlatform/google-cloud-go#716]
The below error happened when I build a program that imports grpc twice (indirectly).

```
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x529a360, 0x4bdc4ad, 0xf, 0x51900c0, 0x4c1d688)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2254 +0x610
net/http.(*ServeMux).HandleFunc(0x529a360, 0x4bdc4ad, 0xf, 0x4c1d688)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2286 +0x55
net/http.HandleFunc(0x4bdc4ad, 0xf, 0x4c1d688)
        /usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2298 +0x4b
golang.org/x/net/trace.init.1()
        /Users/avelino/src/golang.org/x/net/trace/trace.go:115 +0x42
golang.org/x/net/trace.init()
        /Users/avelino/src/golang.org/x/net/trace/trace_go17.go:22 +0x1cd
google.golang.org/grpc.init()
        /Users/avelino/src/google.golang.org/grpc/trace.go:105 +0x87
google.golang.org/genproto/googleapis/cloud/vision/v1.init()
        /Users/avelino/src/google.golang.org/genproto/googleapis/cloud/vision/v1/web_detection.pb.go:194 +0x87
cloud.google.com/go/vision.init()
        /Users/avelino/src/cloud.google.com/go/vision/vision.go:357 +0x52
github.com/nuveo/runners/cicontains.init()
        /Users/avelino/src/github.com/nuveo/runners/cicontains/cicontains.go:150 +0x70
github.com/nuveo/runners/summoner.init()
        /Users/avelino/src/github.com/nuveo/runners/summoner/summoner.go:187 +0x75
github.com/nuveo/instances%2ecore.init()
        /Users/avelino/src/github.com/nuveo/instances.core/instances.go:88 +0x62
github.com/nuveo/application.core/process.init()
        /Users/avelino/src/github.com/nuveo/application.core/process/routers.go:11 +0x8e
main.init()
        /Users/avelino/src/github.com/nuveo/application.core/main.go:48 +0x5d
exit status 2
```

The root cause of the error seems to be the module `golang.org/x/net/trace`. Its init() registers a handler to the same URL (e.g. /debug/requesets). Therefore importing the module more than twice causes the above panic.

I'm not sure here is a suitable place for reporting the problem. I'd like to hear gRPC developers' opinion. Should I go to the issue tracker of golang? Or is a workaround for this problem known?

ref: https://github.com/grpc/grpc-go/issues/566

**Comment by jba** [comment]
How do you import grpc twice? Is vendoring involved?

**Comment by jba** [comment]
Closing due to lack of activity.
