### ISSUE TITLE
BigQuery: panic in uploader on nil values

### ISSUE THREAD

**Issue by jamesonjlee** [GoogleCloudPlatform/google-cloud-go#777]
I had some bad code where I was passing `nil` to the uploader.

since nil is a valid struct pointer, https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/uploader.go#L123 returns with `ss == nil, ok == true`, then `ss.Schema` will panic with nil dereference.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86c2d5]

goroutine 1 [running]:
vendor/cloud.google.com/go/bigquery.toValueSaver(0xc85120, 0x0, 0x196, 0xc85120, 0x0, 0xc420550000, 0x196)
	<snip>/go/src/vendor/cloud.google.com/go/bigquery/uploader.go:123 +0x95
vendor/cloud.google.com/go/bigquery.valueSavers(0xbf3060, 0xc4203885c0, 0xc42064f800, 0x40e4cf, 0xbf3060, 0xc4203885c0, 0xc42064f8c0)
	<snip>/go/src/vendor/cloud.google.com/go/bigquery/uploader.go:103 +0x237
vendor/cloud.google.com/go/bigquery.(*Uploader).Put(0xc42064f8d8, 0x1213de0, 0xc42056ccf0, 0xbf3060, 0xc4203885c0, 0xc42056cdb0, 0x22)
	<snip>/go/src/vendor/cloud.google.com/go/bigquery/uploader.go:80 +0x39
...
<snip>/cmd.pollService(0x1213de0, 0xc4203e1590, 0x1217380, 0xc420025260, 0xc4201614d0, 0x12108a0, 0xc420120dc0, 0x12108e0, 0xc42011f080)
```

this should get caught instead of causing a panic?

**Comment by jba** [comment]
This no longer panics.
