### ISSUE TITLE
trace: test failure

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-go#801]
I saw this trace from https://travis-ci.org/GoogleCloudPlatform/google-cloud-go/jobs/296021791

```
=== RUN   TestGRPCInterceptors
SIGQUIT: quit
PC=0x487289 m=0 sigcode=0
goroutine 0 [idle]:
runtime.epollwait(0x4, 0x7ffcb3cf9090, 0xffffffff00000080, 0x0, 0xffffffff00000000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/sys_linux_amd64.s:560 +0x19
runtime.netpoll(0xc420029301, 0xc420029301)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll_epoll.go:67 +0x91
runtime.findrunnable(0xc420028000, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:2084 +0x33c
runtime.schedule()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:2222 +0x153
runtime.park_m(0xc420001ba0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:2285 +0x7a
runtime.mcall(0x7ffcb3cf9810)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:269 +0x5b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc420181040, 0xfdcca8, 0x14, 0xff8e88, 0xc4200f5c48)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:698 +0x582
testing.runTests.func1(0xc420181040)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:882 +0xab
testing.tRunner(0xc420181040, 0xc4200f5d78)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x108
testing.runTests(0xc420176ea0, 0x1415480, 0x14, 0x14, 0x10000000000)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:888 +0x4e1
testing.(*M).Run(0xc4200f5f28, 0xc4200f5ed0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:822 +0x1c4
main.main()
	cloud.google.com/go/trace/_test/_testmain.go:84 +0x210
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1
goroutine 4 [select]:
google.golang.org/grpc.(*ClientConn).WaitForStateChange(0xc4200d6a00, 0x7fb0ffadd000, 0xc42006cd68, 0x3, 0x1)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:589 +0x19b
google.golang.org/grpc.DialContext(0x7fb0ffadd000, 0xc42006cd68, 0xc42006db10, 0xa, 0xc420045ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:501 +0xd44
google.golang.org/grpc.Dial(0xc42006db10, 0xa, 0xc420045ef8, 0x3, 0x3, 0xc420024660, 0xd8615c, 0xc420017b24)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:357 +0xbd
cloud.google.com/go/trace.testGRPCInterceptor(0xc420181110, 0xc420011aa0, 0xc42019e000, 0xff8e58)
	/home/travis/gopath/src/cloud.google.com/go/trace/grpc_test.go:145 +0x24f
cloud.google.com/go/trace.TestGRPCInterceptors(0xc420181110)
	/home/travis/gopath/src/cloud.google.com/go/trace/grpc_test.go:45 +0xc4
testing.tRunner(0xc420181110, 0xff8e88)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x108
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x544
goroutine 5 [IO wait]:
net.runtime_pollWait(0x7fb0ffaddfa8, 0x72, 0x13ce758)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x5e
net.(*pollDesc).wait(0xc420060fb8, 0x72, 0x13ce758, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x5b
net.(*pollDesc).waitRead(0xc420060fb8, 0xffffffffffffffff, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x42
net.(*netFD).accept(0xc420060f50, 0x0, 0x13d28a0, 0xc420176f40)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:430 +0x2c0
net.(*TCPListener).accept(0xc42000e0c8, 0xc4200263a0, 0xc420046d88, 0x452902)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock_posix.go:136 +0x51
net.(*TCPListener).Accept(0xc42000e0c8, 0xff9f28, 0xc420196420, 0x13da120, 0xc42000e0c8)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x50
google.golang.org/grpc.(*Server).Serve(0xc420196420, 0x13da120, 0xc42000e0c8, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:475 +0x217
cloud.google.com/go/trace.testGRPCInterceptor.func1(0xc420181110, 0xc4200246c0, 0xc420011aa0, 0xc420024660)
	/home/travis/gopath/src/cloud.google.com/go/trace/grpc_test.go:139 +0x31e
created by cloud.google.com/go/trace.testGRPCInterceptor
	/home/travis/gopath/src/cloud.google.com/go/trace/grpc_test.go:142 +0xcd
goroutine 19 [select]:
google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc420073a10)
	/home/travis/gopath/src/google.golang.org/grpc/resolver_conn_wrapper.go:99 +0x5d0
created by google.golang.org/grpc.newCCResolverWrapper
	/home/travis/gopath/src/google.golang.org/grpc/resolver_conn_wrapper.go:84 +0x4f1
goroutine 20 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc420077280)
	/home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:120 +0x4b4
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:111 +0x2e0
goroutine 21 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc4200ae600, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:1010 +0x144d
google.golang.org/grpc.(*addrConn).connect.func1(0xc4200ae600)
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:740 +0x3d
created by google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/src/google.golang.org/grpc/clientconn.go:749 +0x186

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x487289
rdx    0x80
rdi    0x4
rsi    0x7ffcb3cf9090
rbp    0x7ffcb3cf9690
rsp    0x7ffcb3cf9050
r8     0xdd
r9     0x103f4b8
r10    0xffffffff
r11    0x246
r12    0xc420046ba8
r13    0x141dc40
r14    0xc420001ba0
r15    0x6268b3
rip    0x487289
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```

**Comment by jba** [comment]
Fixed in https://code-review.googlesource.com/c/gocloud/+/19152, awaiting approval. Added you as a reviewer (hint...).
